#!/usr/bin/env python2.7
import json
from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter

def main():

    # Add options parser
    parser = ArgumentParser(formatter_class=ArgumentDefaultsHelpFormatter)
    prepare_args(parser)
    args = parser.parse_args()

    arg_dict = {"o-test-int": args.test_int,
                "o-test-str1": args.test_str1,
                "o-test-str2": args.test_str2}

    print(json.dumps(arg_dict, indent=2))

def prepare_args(parser):
    parser.add_argument("--test-int", "-ti", required = True, type=int, help="an int")
    parser.add_argument("--test-str1", "-ts", required = True, type=str, help="a str")
    parser.add_argument("--test-str2", "-tss", required = True, type=str, help="a str")


    parser.add_help = True
    parser.prefix_chars = "-"
    parser.description = "Takes some arguments and spits them back out."

if __name__ == "__main__":
    main()
